version: '2'
services:
  db:
    image: mysql
    volumes:
      - "./sito/db/:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      NAME: 'sed_database',
      MYSQL_USER: 'sed_admin',
      USER: 'sed_admin',
      PASSWORD: 'sed_password',
      MYSQL_ROOT_PASSWORD: 'sed_password',
      MYSQL_PASSWORD: 'sed_password',
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:code"
    ports:
      - "8000:8000"
    depends_on:
      - db
